In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('loanf.csv')
df.head()

Interest.Rate  FICO.Score  Loan.Length  Monthly.Income  Loan.Amount
6           15.31         670           36         4891.67         6000
11          19.72         670           36         3575.00         2000
12          14.27         665           36         4250.00        10625
13          21.67         670           60        14166.67        28000
21          21.98         665           36         6666.67        22000

In [3]:
df.shape

(2500, 5)

In [4]:
df.describe()

Interest.Rate   FICO.Score  Loan.Length  Monthly.Income   Loan.Amount
count    2500.000000  2500.000000  2500.000000     2499.000000   2500.000000
mean       13.066996   705.888000    41.260800     5688.931321  12406.500000
std         4.178230    35.033161     9.930893     3963.118185   7801.544872
min         5.420000   640.000000    36.000000      588.500000   1000.000000
25%        10.160000   680.000000    36.000000     3500.000000   6000.000000
50%        13.110000   700.000000    36.000000     5000.000000  10000.000000
75%        15.800000   725.000000    36.000000     6800.000000  17000.000000
max        24.890000   830.000000    60.000000   102750.000000  35000.000000

In [5]:
df.isna().sum()

Interest.Rate     0
FICO.Score        0
Loan.Length       0
Monthly.Income    1
Loan.Amount       0
dtype: int64

In [6]:
df['Interest.Rate']

6       15.31
11      19.72
12      14.27
13      21.67
21      21.98
        ...  
2472     7.90
2481     6.03
2482     6.62
2486    10.75
2497    14.09
Name: Interest.Rate, Length: 2500, dtype: float64

In [7]:
## One the base of interest column we define that if our interest rate is less than 17.0 then loan approved else not
df['Loan_AN'] = df['Interest.Rate'] < 17.0  

In [8]:
df.head()

Interest.Rate  FICO.Score  Loan.Length  Monthly.Income  Loan.Amount  \
6           15.31         670           36         4891.67         6000   
11          19.72         670           36         3575.00         2000   
12          14.27         665           36         4250.00        10625   
13          21.67         670           60        14166.67        28000   
21          21.98         665           36         6666.67        22000   

    Loan_AN  
6      True  
11    False  
12     True  
13    False  
21    False

In [9]:
df.keys()

Index(['Interest.Rate', 'FICO.Score', 'Loan.Length', 'Monthly.Income',
       'Loan.Amount', 'Loan_AN'],
      dtype='object')

__Lets take FICO.score and Loan.Amount as dependent columns and Loan_AN is our dependent column.__



In [10]:
x = df[['FICO.Score', 'Loan.Amount']].values
y = df.Loan_AN.values

In [11]:
print(y)
x

[ True False  True ...  True  True  True]


array([[  670,  6000],
       [  670,  2000],
       [  665, 10625],
       ...,
       [  810, 27000],
       [  765, 25000],
       [  740, 16000]], dtype=int64)

### Apply logistic regressioin

In [12]:
log_model = LogisticRegression()

In [13]:
log_model.fit(x,y)

LogisticRegression()

In [14]:
## Check the prediction of our model
newX = x[3]
newy = y[3]

In [15]:
log_model.predict([newX]) , newy

(array([False]), False)

In [16]:
log_model.predict_proba([newX])  ## returns a probability in array as [Not_Approved(False), Approved(True)]

array([[0.52081392, 0.47918608]])

In [49]:
fico[0]

300

In [40]:
## Lets check for own data
log_model.predict([[500, 30000]])

TypeError: predict() missing 1 required positional argument: 'X'

__Built a function and apply condition that if probability is more than 80% your loan will approved otherwise not.__

In [51]:
def LoanAN(FICO, Amount):
    out = log_model.predict_proba([[FICO, Amount]])[0][1]
    
    if out > 0.8:
        print("#####Congrats your loan is approved########")
    
    else:
        print(".......Your loan is not approved..........(:")

In [52]:
fico, amount = 300 , 5000
fico = np.array([fico, amount])
# amount = np.array(amount)
# fico
LoanAN(fico[0], fico[1])

.......Your loan is not approved..........(:


In [55]:
from ipywidgets import interact

In [57]:
interact(LoanAN, FICO=(200, 1000), Amount=(1000, 35000))

interactive(children=(IntSlider(value=600, description='FICO', max=1000, min=200), IntSlider(value=18000, desc…

<function __main__.LoanAN(FICO, Amount)>

__Store the model in pickle file.__

In [59]:
# Here, we will save the 'lr' model to disk as 'model.py'
import pickle

# Dump this model by the name "model.py" in the systems HDD and while doing this
# write this file using "write bytes" mode.

pickle.dump(log_model, open('Loan_AN_LR_Model.pkl','wb'))

In [ ]:
# from sklearn.externals import joblib
# !conda install joblib


In [ ]:
# !pip install joblib